INSERT INTO users(user_name, first_name, last_name, user_password, youtube_channel) VALUES ('no_filter_bbq', 'Tim', 'Galloway', '!QAZ2wsx#4','None');
INSERT INTO users(user_name, first_name, last_name, user_password, youtube_channel) VALUES ('therealest', 'Heinz','Ward', 'Gall1984','None');
INSERT INTO users(user_name, first_name, last_name, user_password, youtube_channel) VALUES ('NoDubt', 'Jenna', 'Fischer', 'gee123','None');
INSERT INTO users(user_name, first_name, last_name, user_password, youtube_channel) VALUES ('GavinR', 'Gavin', 'Rossdale', 'Bush4Life','None');

INSERT INTO bourbonForum(user_id, comment, post_date) VALUES (1, 'Hello BBQ and Bourbon Community!', '11 May 2023');
INSERT INTO bourbonForum(user_id, comment, post_date) VALUES (2, 'I truly enjoy a good Jim Beam Black on ice the best.', '11 May 2023');
INSERT INTO bourbonForum(user_id, comment, post_date) VALUES (3, '@no_filter_bbq you are awesome for setting this page up.', '10 May 2023');
INSERT INTO bourbonForum(user_id, comment, post_date) VALUES (4, 'When we were young our future was so bright.  Every kid on the street was going to make it be an MVP', '8 May 2023');
INSERT INTO bourbonForum(user_id, comment, post_date) VALUES (2, 'Bourbon with Splenda....takes like Splenda burns like Bourbon, lol', '9 May 2023');
INSERT INTO bourbonForum(user_id, comment, post_date) VALUES (3, 'Sometimes I do the cha cha like a sissy girl', '10 May 2023');

INSERT INTO bbqForum(user_id, comment, post_date) VALUES (1, 'Ready to do some BBQ!', '11 May 2023');
INSERT INTO bbqForum(user_id, comment, post_date) VALUES (1, 'I have brisket ready to go!', '11 May 2023');
INSERT INTO bbqForum(user_id, comment, post_date) VALUES (2, 'What is everyone are plans this weekend?', '11 May 2023');
INSERT INTO bbqForum(user_id, comment, post_date) VALUES (3, 'Anyone want to meet up and enjoy some STL Style Ribs?', '11 May 2023');
INSERT INTO bbqForum(user_id, comment, post_date) VALUES (4, 'Thinking of doing a whole hog.  How would you all start it?', '11 May 2023');
INSERT INTO bbqForum(user_id, comment, post_date) VALUES (4, 'Decided to go with just a pork belly for some pork belly bombs.', '11 May 2023');

INSERT INTO bbqRecipies(user_id, title, ingredients, steps, temperature, post_date) VALUES (1, 'Pulled Pork', 'pork shoulder, Killer Hogs Seasoning, Mustard, Apple Juice', 'Inject shoulder with juice, rub with mustard then seasoning.  Then put on smoker for 8 hours or internal temperature of 190-195 degrees.  Then remove wrap, if not already, and place in cooler for 1 hour.', 225, '14 February 2023');
INSERT INTO bbqRecipies(user_id, title, ingredients, steps, temperature, post_date) VALUES (2, 'Pork Steaks','pork steaks, Killer Hogs Seasoning, Mustard', 'Rub with mustard then seasoning.  Then put on smoker for 4 hours or internal temperature of 190-195 degrees. Serve when tender.', 250, '10 March 2023');
INSERT INTO bbqRecipies(user_id, title, ingredients, steps, temperature, post_date) VALUES (3, 'Pork Belly Bombs', 'pork belly, pan with alumnim foil, BBQ sauce, Killer Hogs Seasoning, and Mustard', 'Slice off pork belly skin.  Then cut into one inch strips.  Then cut strips into one inch cubes.  Roll cubes in mustard and then into seasoning.  Place on rack keeping about 1/2 inch space between.  Smoke for 3 hours then remove, sauce with favorite bbq sauce, then put back on smoker in foil covered pan.  Smoke for an additional hour.', 225, '6 January 2023');
INSERT INTO bbqRecipies(user_id, title, ingredients, steps, temperature, post_date) VALUES (4, 'Lolipop Chicken','Chicken Drumbsticks, Meat Church Honey Chicken seasoning, Irish Butter, Brownie pans, Bacon, and BBQ sauce', 'Cut skin, tendons, and ligaments off knuckle of bone and remove thin bone along main bone.  Pull meat down to bottom.  Wrap bacon around bone stem.  Season and then add to brownie pan.  Slice up one stick of butter and place on top and around chicken.  Smoke until internal of 165. Then remove and sauce up!', 225, '1 May 2023');
INSERT INTO bbqRecipies(user_id, title, ingredients, steps, temperature, post_date) VALUES (3, 'Whole Ham', 'Pork Shank Whole unspiraled cut, Mustard, Meat Church Whole Hog seasoning, Dr. Pepper, Brown Sugar, Cherries, Cherry Juice, Pineapple Juice', 'Trim pork and then rub in mustard and seasoning.  Add probe for better readings on temp and place in smoker.  Then bring other ingredients in pot to boil and cool.  When pork hits temp of 135 brush on boiled ingredients and continue every 30 minutes until internal reaches 170 degrees.  Wrap pork and put back on smoker until internal hits 195.', 200, '12 May 2023');

INSERT INTO bourbonReviews(user_id, bourbon_type, bourbon_name, review, notes) VALUES (1, 'Rye', 'Rabbit Hole', 'Sweet yet subtle profile with a mix of smoke and a smooth burn at the end.', 'Cherry, Oak, Wheat, and Cinnamon');
INSERT INTO bourbonReviews(user_id, bourbon_type, bourbon_name, review, notes) VALUES (2, 'Bourbon', 'Knob Creek 9 year', 'Soft underbelly with a hint of cinnamon at the start.  Finishes smooth with notes of maple, cherry, and apples that runs back up the tongue.', 'Oak, Apples, Maple, and Cinnamon');
INSERT INTO bourbonReviews(user_id, bourbon_type, bourbon_name, review, notes) VALUES (3, 'Bourbon', 'Old Forrester Prohibition Style', 'This is one for the ages.  I would drink this straight, do not mix!', 'Plums, Orange, Cheery, and Cinnamon');
INSERT INTO bourbonReviews(user_id, bourbon_type, bourbon_name, review, notes) VALUES (4, 'Rye', 'Old Forrester', 'My old man loved this one.  Kick back, put on the game and enjoy with ice or straight.', 'Barley, Hops, smoke, peate, and apples');
INSERT INTO bourbonReviews(user_id, bourbon_type, bourbon_name, review, notes) VALUES (1, 'Bourbon', 'WhistlePig 14', 'This one will kick you in the back and in the front of the mouth.  Get ready!', 'Oak, smoke, cheery, rose, and cinnamon');